stages:
  - deploy

image: rdpascua/ci-pipeline-php

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

deploy_live:
  stage: deploy
  environment:
    name: live
    url: revlv.com
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh revlv@revlv.com "cd /home/revlv/revlv.com && git pull origin master && ./compile.sh"
  only:
    - master